### ISSUE TITLE
Sites already in whitelist blocked by ScriptSafe

### ISSUE THREAD

**Issue by bhall7** [andryou/scriptsafe#41] opened 2016-06-13 00:45 UTC
Hello,

I'm having a strange issue on ScriptSafe v1.0.7.10: After updating to the latest version and synchronizing my settings/whitelist from my Google account to one of my other machines, there are sites that are in the whitelist (for example, *.twitter.com), that are still being blocked by ScriptSafe. When I attempt to trust the site, the following message displays:

> ScriptSafe detected 1 existing rule(s) for twitter.com (1 whitelist and 0 blacklist).
> Do you want to delete them in order to avoid conflicts?
> Note: this might not necessarily remove all conflicting entries, particularly if they use regex (e.g. d?main.com).

If I select OK, I then need to refresh the page before ScriptSafe will allow the site.

This is happening on two different machines that I use to sync my settings using my Google account.

**Comment by andryou** [comment] 2016-06-13 01:24
Thanks for the report! So if you add *.twitter.com to your whitelist and visit www.twitter.com, it's not whitelisted?

There are some things in the new domain matching syntax to be aware of:

**.domain.com = will match domain.com, www.domain.com, abc.def.domain.com ("Trusting" a domain)
*.domain.com = will match www.domain.com, abc.domain.com, but not domain.com or abc.def.domain.com
domain.com = will match domain.com and www.domain.com, but not abc.domain.com

Some more info here: https://github.com/andryou/scriptsafe/wiki/Domain-Lists

If you don't mind providing an entry example and sample page, I can help double-check if there is an issue. Thanks!

**Comment by rogor** [comment] 2016-06-13 22:34
Hey!

I have the same issue on Linux Mint 17.2 with Chrome 51.0.2704.84.
After syncing the settings from my google account, domains are not allowed despite already being in the whitelist.

It seems that the issue is only present with this type of entry in the whitelist: **\*.domain.com**
- If I allow the domain, it is no more blocked and an entry is added to the whitelist : **domain.com**  (**\*.domain.com** is still present in the whitelist)
- If I trust the domain (and select OK on the existing rule warning), it is no more blocked and  the entry in the whitelist becomes **\*\*.domain.com**

**Comment by andryou** [comment] 2016-06-13 22:45
There was a one-time function that ran to convert all previously trusted sites to the new format (*.domain.com to **.domain.com).

My guess is that it was overwritten by the settings synced from your Google Account.

One way to resolve this is to manually re-trust each site; another is to copy/paste the export text into a text editor, search and replace all *. with **, then re-import it back.

And then in the Options page, click on "Sync Settings TO Google Account" to ensure that the updates are synced to your other devices.

**Comment by bhall7** [comment] 2016-06-14 00:12
Something weird is definitely happening. I have two machines both synchronizing settings via Google. On one of them, the sites in the whitelist are showing correctly (e.g., `**.domain.com`), but on my other one, it's showing some as `**.domain.com` and others as `*.domain.com`.

On the machine with the good settings, I went to the ScriptSafe options and clicked "Sync Settings TO Google Account." On the machine with the messed up settings, I sent to the ScriptSafe Options and clicked "Sync Settings FROM Google Account." However, the settings on the second machine were still messed up.

The only way I was able to solve this was to manually export the settings from the machine with the good, known settings to a TXT file, then import them into the machine with the messed up settings. I then did a test where I made changes on each machine and I saw the changes sync between both machines. So, whatever was messing things up before was resolved by copying the settings from one machine to the other.

**Comment by andryou** [comment] 2016-06-14 00:32
Thanks for the troubleshooting and my apologies for all the trouble. I am crossing my fingers that you will not need to do all this work in the future again!

I'm trying to think of how I can help tackle this issue, but all answers lead to very risky solutions that involve tinkering with people's whitelist/blacklists (and syncing), which I want to avoid as much as possible as I'd consider it to be quite invasive. I'm not sure if you want to close this issue; if there is anything I can do to help, please let me know.

I do hope v1.0.7.11 is running well otherwise for you!

**Closed** 2016-06-14 00:47 UTC

**Comment by gypsy56** [comment] 2018-03-24 06:57
I have **ton.twimg.com in the whitelist but each time I go to tweetdeck.twitter.com again I have to trust the domain again.
