### ISSUE TITLE
Microsoft.com Sign In

### ISSUE THREAD

**Issue by rykel** [andryou/scriptsafe#118] opened 2016-10-05 09:59 UTC
I cannot use microsoft.com with my signed in Microsoft Account, until and unless I totally disable ScriptSafe. Please help?

**Comment by downlz** [comment] 2016-11-30 06:54
yeah same here.I was working initially after trusting the source but it's no longer working after the sync.

**Comment by andryou** [comment] 2016-12-23 20:55
v1.0.8.5 has officially been released. Could you please retest (once you verify that ScriptSafe v1.0.8.5 is installed) and let me know if the issue is still present? Thanks!

**Comment by flex-lm** [comment] 2017-01-23 20:26
I think that #163 could be related to problems on the Microsoft website.

**Comment by flex-lm** [comment] 2017-01-26 20:59
The Microsoft website (including log in functionality) is now working on my end with version 1.0.9.1

**Comment by andryou** [comment] 2017-01-26 21:13
@flex-lm thanks for testing! I've also tested and was able to log in and navigate some pages. I'll close this but will be happy to re-open if Microsoft isn't working for others.

**Closed by andryou** 2017-01-26 21:13 UTC
