### ISSUE TITLE
"Respect Same-Domain" doesn't work?

### ISSUE THREAD

**Issue by at0micboy** [andryou/scriptsafe#27] opened 2016-06-06 07:43 UTC
![unbenannt](https://cloud.githubusercontent.com/assets/19772665/15815075/cb31dd06-2bca-11e6-8b29-a405024cb75f.JPG)
After new update "Respect Same-Domain" doesn't works.
"Respect Same-Domain" is active but scriptsafe blocks facebook.com on facebook.com.
Bug?

**Comment by at0micboy** [comment] 2016-06-06 07:44
Thanks for scriptsafe, i love it :)

**Comment by Aybee** [comment] 2016-06-06 11:24
Yes, I also have many problems with latest version 1.0.7.7. Sadly I have to disable scriptsafe. is there a way to downgrade it?

**Comment by andryou** [comment] 2016-06-06 13:13
@at0micboy and @Aybee: I apologize for the delay in getting v1.0.7.8 to you (which reverts back to the original "Respect Same-Domain" behaviour, this was reported in #25); I checked and it's still "Pending Review" in the Chrome Web Store. I had pushed it out almost 12 hours ago.

You can find all releases here: https://github.com/andryou/scriptsafe/releases ("LEGACY" builds do not have WebRTC Protection). Give v1.0.7.8 a try and let me know if it resolves this issue, before going back to v1.0.7.6 if it doesn't. Hopefully Chrome approves v1.0.7.8 soon.

**Comment by at0micboy** [comment] 2016-06-06 14:48
Sorry for duplicate and thanks a lot

**Comment by chrcoluk** [comment] 2016-06-06 17:17
and a +1 from me, lately the updates have been way too rapid, please dont do android rapid style updates without testing, make a beta version for this.

**Comment by andryou** [comment] 2016-06-06 17:24
@chrcoluk noted. I think things will settle down from this point on (after v1.0.7.8 is approved in the web store and pushed out, which fixes this issue). In terms of updates, I will spend more time testing before pushing any out.

**Comment by andryou** [comment] 2016-06-06 17:26
Closing this issue as it is a duplicate of #25.

**Closed by andryou** 2016-06-06 17:26 UTC
Labels: duplicate
