### ISSUE TITLE
UA spoof stops working after Temp permission

### ISSUE THREAD

**Issue by LeeUK** [andryou/scriptsafe#53] opened 2016-06-22 16:11 UTC
Hi,

The UA Spoof works fine when JS is otherwise 'disabled' by ScriptSafe. As soon as Temp permissions are granted however, the spoofing seems to stop. I'm unsure if this is by design, or a bug? If by design, perhaps an option to continue the spoof even after deciding to grant permission for JS to run on a given site could be implemented?

Awesome plugin. One of my absolute favourite "must-haves". Thank you.

**Comment by andryou** [comment] 2016-06-22 19:47
Excellent suggestion. Yes that is expected behaviour (because one example is it interferes with Gmail), but I will add in a checkbox labelled "Apply to allowed sites as well"!

**Comment by andryou** [comment] 2016-06-22 20:30
Beta version addresses this :) See: #54

**Comment by LeeUK** [comment] 2016-06-23 10:24
Sorry for the late reply. Bravo sir, bravo! 

I see your (very valid) point about the reasons behind turning it off after JS is allowed. Those of us who fiddle with that bit will probably appreciate the option for it to persist though; and we can always nuke it if it continues to cause issues. :)

**Comment by andryou** [comment] 2016-06-30 16:19
@LeeUK I've just officially pushed out v1.0.8.0, which contains this fix. Feel free to test it out when it arrives on your machine and close this ticket :)

**Closed** 2016-12-24 03:03 UTC
Labels: enhancement
